In [26]:
import pandas as pd
import numpy as np

### Q1. Pandas version

In [2]:
pd.__version__

'3.0.6'

### Q2. Records count

In [16]:
data = pd.read_csv('data/car_fuel_efficiency_2026.csv')
df = data.copy()

# Total records
total_records = len(df)
print(total_records)

10000


In [17]:
df.head(5)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


### Q3. Fuel types

In [5]:
# Find fuel types
fuel_types = df['fuel_type'].unique().tolist()
print(fuel_types)

['Gasoline', 'Diesel', 'Hybrid']


### Q4. Missing values

In [6]:
# Find missing values
missing_values = df.isnull().sum()
print(missing_values)

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64


### Q5. Max fuel efficiency

In [8]:
# Max fuel efficiency
max_fuel_efficiency = df['fuel_efficiency_mpg'].max()
print(max_fuel_efficiency)

41.2


### Q6. Median value of horsepower

In [10]:
# Median value of horse power
median_horse_power = df['horsepower'].median()
print(median_horse_power)

254.0


In [11]:
# Most frequent value of horse power
most_frequent_horse_power = df['horsepower'].mode()[0]
print(most_frequent_horse_power)

252.0


In [13]:
# Filling missing values in horsepower with most frequent value
df['horsepower'] = df['horsepower'].fillna(most_frequent_horse_power)

In [15]:
# Median value of horse power
median_horse_power = df['horsepower'].median()
print(median_horse_power)

252.0


### Q7. Sum of weights

In [19]:
# Select all the cars from Asia
df_asia = df[df['origin'] == 'Asia']

In [20]:
# Select only columns vehicle_weight and model_year
df_selected = df_asia[['vehicle_weight', 'model_year']]

In [ ]:
# Select the first 7 values
first_seven_values = df_selected.head(7)

In [24]:
# Get the underlying NumPy array. Let's call it X.
x = first_seven_values.values
print(x)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]


In [25]:
# Compute matrix-matrix multiplication between the transpose of X and X
X_transpose_X = x.T @ x
print(X_transpose_X)

[[131950500  60750580]
 [ 60750580  28041424]]


In [27]:
# Invert XTX
XTX_inverse = np.linalg.inv(X_transpose_X)
print(XTX_inverse)

[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]


In [28]:
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200]
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
print(y)

[1100 1300  800  900 1000 1100 1200]


In [29]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
res1 = XTX_inverse @ x.T
w = res1 @ y
print(w)

[0.13644777 0.2327492 ]


In [30]:
# Sum of all the elements of the result
sum_w = np.sum(w)
print(sum_w)

0.36919696904925486
